### ISSUE TITLE
how does this plugin work?

### ISSUE THREAD

**Issue by Legendmanj** [4drian3d/KickRedirect#61]

**Comment by yusshu** [comment]
borra tu cuenta porfa

**Comment by 4drian3d** [comment]
KickRedirect, as stated on the main page, works in a similar way to how Velocity's redirect system works, every time a server goes down or is shut down or the player is kicked, it prevents them from being permanently kicked out of Velocity by redirecting them to an available configured server.
Please read the main page of each plugin before making an unnecessary issue.
