### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by Pantera07** [4drian3d/KickRedirect#79]
@4drian3d 
![aa](https://github.com/4drian3d/KickRedirect/assets/89838384/d5e5112b-d58b-4a10-aeca-954051a31ea6)

Color errors occur when used with the latest Velocity.

**Comment by 4drian3d** [comment]
Thank you very much for reminding me, this bug was solved months ago but I forgot to make a release

**Comment by 4drian3d** [comment]
Fixed in the latest release
